const postReducerActions = {
  LOADING: 'LOADING',
  ERROR: 'ERROR',
  POSTS_FETCH_SUCCESS: 'POSTS_FETCH_SUCCESS',
  USERS_POSTS_FETCH_SUCCESS: 'USERS_POSTS_FETCH_SUCCESS',
  SINGLE_POST_FETCH_SUCCESS: 'SINGLE_POST_FETCH_SUCCESS',
  POST_CREATE: "POST_CREATE",
  POST_DELETE: "POST_DELETE",

  COMMENT_ADDED: "COMMENT_ADDED",
  COMMENT_DELETED: "COMMENT_DELETED",

  FETCH_REACTION_EMOJIS: "FETCH_REACTION_EMOJIS",

  REACTION_ADDED: "REACTION_ADDED",
  REACTION_REMOVED: "REACTION_REMOVED",
  REACTION_UPDATED: "REACTION_UPDATED",
  REACTION_REVERTED: "REACTION_REVERTED",

};

export default postReducerActions;