export const postReducerActions = {
  LOADING: 'LOADING',
  ERROR: 'ERROR',
  POSTS_SUCCESS: 'POSTS_SUCCESS',
  USERS_POSTS_SUCCESS: 'USERS_POSTS_SUCCESS',
  POST_SUCCESS: 'POST_SUCCESS',
  POST_DELETE: "POST_DELETE",
  POST_CREATE: "POST_CREATE"
};