export const userReducerActions = {
  LOADING: 'LOADING',
  ERROR: 'ERROR',
  USERS_SUCCESS: 'USERS_SUCCESS',
  USER_ACTIVATE: 'USER_ACTIVATE',
  USER_DEACTIVATE: 'USER_DEACTIVATE',
  USER_DELETE: "USER_DELETE",
  USER_CREATE: "CREATE_USER",
  USER_FETCH_SUCCESS: "USER_FETCH_SUCCESS"
};